### ISSUE TITLE
add eer support for the tasks protocol

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-motioncorr#108]
Does mc2 support batch mode for eer? @delarosatrevin ?

**Comment by delarosatrevin** [comment]
Not sure @azazellochg. I might contact Shawn and ask him. It would be great if there is support. I was also thinking about MC3. If EER is not supported, it would be interesting to do some performance benchmarks of one-by-one EER processing vs first converting EER to TIFF and then batch processing.

**Comment by azazellochg** [comment]
it is implemented long ago according to readme:
09-25-2020
----------
1.4.0
1. Implemented sequential processing for EER movies
