### ISSUE TITLE
Ts MC failing when EER sampling is higher than 50

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em-motioncorr#114]
Reported by one of our users. He says that with values of 20 or 50 it works, but not with higher. He needs to pile 110 frames to get a dose of 0.5. The error is basically that motioncorr fails and exits. Any idea? 

00008:   ERROR: Motioncor has failed for Runs/000002_ProtImportTsMovies/extra/S1_Position_1_001_0.00_20241128_231912_EER.eer --> Command ' /software/motioncor3/bin/MotionCor3  -InEer "/mnt/cryoemgfs/data/cryoem/ScipionUserData/projects/2024_11_28_Francisco-GPortillo_000236/Runs/000002_ProtImportTsMovies/extra/S1_Position_1_001_0.00_20241128_231912_EER.eer" -Throw 0 -Trunc 0 -Patch 0 0 -MaskCent 0 0 -MaskSize 1 1 -FtBin 2.0 -Tol 0.2 -PixSize 2.2 -kV 200.0 -Cs 0 -OutStack 0 -Gpu 0 -SumRange 0.0 0.0 -LogDir ./ -EerSampling 1 -FmIntFile ../../extra/FmIntFile.txt -Group 1 4 -Gain "/mnt/cryoemgfs/data/cryoem/ScipionUserData/projects/2024_11_28_Francisco-GPortillo_000236/Runs/000262_ProtTsMotionCorr/extra/20241105_121552_EER_GainReference.mrc" -RotGain 0 -FlipGain 0 -OutMrc "../../extra/S1_Position_1_01.mrc" ' returned non-zero exit status 139.
00009:   
00010:   Traceback (most recent call last):
00011:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/motioncorr/protocols/protocol_ts_motioncor.py", line 92, in _processTiltImageM
00012:       self.runJob(Plugin.getProgram(), params,
00013:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1545, in runJob
00014:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00015:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 68, in runJob
00016:       process.runJob(log, programName, params,
00017:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 56, in runJob
00018:       return runCommand(command, env=env, cwd=cwd, executable=executable)
00019:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 71, in runCommand
00020:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00021:     File "/software/miniforge3_envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00022:       raise CalledProcessError(retcode, cmd)
00023:   subprocess.CalledProcessError: Command ' /software/motioncor3/bin/MotionCor3  -InEer "/mnt/cryoemgfs/data/cryoem/ScipionUserData/projects/2024_11_28_Francisco-GPortillo_000236/Runs/000002_ProtImportTsMovies/extra/S1_Position_1_001_0.00_20241128_231912_EER.eer" -Throw 0 -Trunc 0 -Patch 0 0 -MaskCent 0 0 -MaskSize 1 1 -FtBin 2.0 -Tol 0.2 -PixSize 2.2 -kV 200.0 -Cs 0 -OutStack 0 -Gpu 0 -SumRange 0.0 0.0 -LogDir ./ -EerSampling 1 -FmIntFile ../../extra/FmIntFile.txt -Group 1 4 -Gain "/mnt/cryoemgfs/data/cryoem/ScipionUserData/projects/2024_11_28_Francisco-GPortillo_000236/Runs/000262_ProtTsMotionCorr/extra/20241105_121552_EER_GainReference.mrc" -RotGain 0 -FlipGain 0 -OutMrc "../../extra/S1_Position_1_01.mrc" ' returned non-zero exit status 139.
00024:   Traceback (most recent call last):
00025:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 207, in run
00026:       self._run()
00027:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 257, in _run
00028:       resultFiles = self._runFunc()
00029:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _runFunc
00030:       return self._func(*self._args)
00031:     File "/software/miniforge3_envs/scipion3/lib/python3.8/site-packages/motioncorr/protocols/protocol_ts_motioncor.py", line 123, in processTiltImageStep
00032:       raise FileNotFoundError(f"Expected output file '{tiFn}' not produced!")
00033:   FileNotFoundError: Expected output file 'Runs/000262_ProtTsMotionCorr/extra/S1_Position_1_01.mrc' not produced!

**Comment by azazellochg** [comment]
Hi @JorMaister , can the user run the cmd command outside scipion? If it segfaults then it is motioncor problem, not scipion

**Comment by azazellochg** [comment]
I can reproduce the issue with a EER movie of 434 frames: if I group 110 it segfaults, if I group much less then it works. You could open an issue https://github.com/czimaginginstitute/MotionCor3/issues
