### ISSUE TITLE
motioncorr does not write out FAILED_all.txt file anymore 

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-motioncorr#16]
Hi,

I noticed that the FAILED_all.txt file is not written out anymore during motion correction. This was very useful for identifying movies that failed to align. Is there anyway to get this back? in 2.0?

Edit: I compared protocol_align_movies.py in 1.21 and 2.0 and all the code that generates the FAILED_all.txt list is missing from 2.0. I suppose I can try copying the relevant code to get this working again but is it at all possible to add back the functionality in the future? Thank you!

**Comment by delarosatrevin** [comment]
Thanks for posting the issue here @andreanans. For the future feel free to post wherever you want and we can book it in the proper place. 

We will bring this functionality back, I agree that is quite useful to know the failed ones.
