### ISSUE TITLE
motioncorr does not/cannot add micrograph to the output if MPI is bigger that 1

### ISSUE THREAD

**Issue by mohsenkazemi** [scipion-em/scipion-em-motioncorr#20]
If I set the number of MPI any number rather than 1, a huge number of micrographs will not be added to the output (or actually, were not generated). The error is like that:

WARNING: Micrograph Runs/000085_ProtMotionCorr/extra/FoilHole_16186163_Data_16188035_16188036_20190819_1352-128194_aligned_mic.mrc was not generated, can't add it to output set.

WARNING - Failed to align 3473 movies.

The number of failed movies depend on the number of MPI! the bigger number for MPI, the more micrographs are not generated.

It works perfectly when the MPI is 1, consequently running slow.

Ubuntu 16, Scipion V.2

**Comment by azazellochg** [comment]
@mohsenkazemi I need more info. Could you provide full run.stdout, GPU IDs and if you run in streaming?

**Comment by azazellochg** [comment]
closed since no reply from the author

**Comment by mohsenkazemi** [comment]
@azazellochg  sorry, I just saw this comment! Still the problem exists. I will open another issue in next weeks, as soon as I get back to the office.

**Comment by azazellochg** [comment]
Hi,

Sure, feel free to reopen this one.
