### ISSUE TITLE
cleanup results in extra folder

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-motioncorr#21]
1) remove DONE_movie_id.txt or move them to DONE folder like in gctf case - pyworkflow repo?
2) move *.log from extra to logs folder

**Comment by delarosatrevin** [comment]
Yes, we need to check to remove all DONE files at the end...but we could try to handle it generally in the pyworkflow-em plugin (not yet separated).

**Comment by azazellochg** [comment]
This will be done in scipion-em repo
