### ISSUE TITLE
Autodetect cuda version vs binary?

### ISSUE THREAD

**Issue by rsanchezgarc** [scipion-em/scipion-em-motioncorr#22]
Hello,

Apparently, MOTIONCOR2_BIN is hard-coded in the protocolol and it is limited to cuda8 and if you want to change it, you have to edit config file. Wouldn't it be possible to autodetect which cuda version is configured in scipion?

**Comment by azazellochg** [comment]
Hi @rsanchezgarc 
This is the case for any package in scipion now. While I agree it could be useful, there is no simple one-to-one-match of mc2 version vs cuda version, e.g. 1.2.6. supports 8.0, 9.2,10.1 but 1.2.3 supports 8.0,9.1,9.2,10.1. Then there is xmipp that supports only cuda 8.0 (hence it's default now). Or imagine if user has cuda9.0 but there is no matching mc2 binary....

I'd prefer to keep things as they are now, to have a default version working in most environments. Cuda version/binary will be updated when scipion/xmipp does. I don't see a problem of setting your config to whatever versions you want. @delarosatrevin any opinion on this?

**Comment by delarosatrevin** [comment]
I think that is a complicated issue, although I agree that could be good to determine the current cuda in the config step. Anyway, in some systems there are more than one cuda...and we need to deal with programs that require different cuda versions, so I don't see any general solution here.

**Comment by delarosatrevin** [comment]
I propose to close this issue here and maybe open an "improvement" one in the base repo, but still not sure if this could be addressed/improved in the near future.

**Comment by rsanchezgarc** [comment]
Ok. But still I think that doing some type of automatical trials when installing the binaries would be great, as most user won't care about the version of the binary but having it working easily.

**Comment by delarosatrevin** [comment]
Thanks for your feedback @rsanchezgarc! I agree that there is room for improvement. I would be good even to detect some configuration problems during installation and not later during processing.
