### ISSUE TITLE
add batch options

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-motioncorr#23]
take into account gpu queuing

**Comment by delarosatrevin** [comment]
What do you mean by gpu queuing?

**Comment by azazellochg** [comment]
you thread implementation to submit movies to different gpus

**Comment by delarosatrevin** [comment]
Ah, ok..I think this is available at step level, we only need to make sure we use the %(GPU) token when forming the command line.

**Comment by azazellochg** [comment]
It appears that the core protocol does not support batches, so this is delayed.
