### ISSUE TITLE
Movies are no saved

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-motioncorr#27]
Hi,

When motioncor is launched with the option save movie enable. The aligned movies are not saved. The output is properly created, the protocol does not fail, however, the output aligned movies make referece to files that do not exit, and therefore they are not shown

**Comment by azazellochg** [comment]
Hi @Vilax I couldn't reproduce this with Scipion 2.0 and devel/master plugin version.

**Comment by Vilax** [comment]
Thank you for over it

I will go over it to see what exactly was failing, I will let you know in next days

**Comment by azazellochg** [comment]
@Vilax any update on this? :)
