### ISSUE TITLE
cannot show FAILED movies

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-motioncorr#30]
Hi,

I was pleased to find the Show FAILED movies button when displaying the outputs from motioncor2. Unfortunately this doesn't seem to work. I see this error when clicking the button:
ProtMotionCorr object has no attribute '_readFailedList'

I updated the motioncor plugin to the latest version (it appears as 1.3.0). Please let me know if there's anything I can do to trouble-shoot.

**Comment by azazellochg** [comment]
Hi @andreanans I'm afraid this will work only with future Scipion release (this summer), since the required changes are also in the core.
