### ISSUE TITLE
creating failed subset failed

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-motioncorr#41]
The subset protocol works, but no output is registered

**Comment by azazellochg** [comment]
@pconesa I might need some help here. If I have a few failed movies, I can display them and when I click Movies button to create a subset it works, but no output is registered:

![image](https://user-images.githubusercontent.com/6952870/106359090-3f6e1800-6308-11eb-967a-6c875674cd67.png)

**Comment by pconesa** [comment]
Left my my charger in the lab on Friday. I'll see if I can do something on the weekend otherwise, on Monday I should go back to the lab and have a look.

**Comment by pconesa** [comment]
What is in the subset status sqlite.? Does it look like the original one? Any log ?

**Comment by azazellochg** [comment]
thank you! you don't need to look at it on the WE :)

**Comment by azazellochg** [comment]
[subset.sqlite.zip](https://github.com/scipion-em/scipion-em-motioncorr/files/5898130/subset.sqlite.zip)

**Comment by pconesa** [comment]
Showing failed movies worked for me....looking into the sqlites.

**Comment by pconesa** [comment]
Wait, I didn't pay attention, it also does not generate an output.

**Comment by azazellochg** [comment]
Yes that's the problem

**Comment by pconesa** [comment]
Ok, it seems I've cancel that behaviour while fixing a similar case for volumes:
https://github.com/scipion-em/scipion-em/commit/ea7c74d652fd23a2989582f9e657b52a39497023
