### ISSUE TITLE
Version for CUDA 10.1 is exeuted, even though CUDA 10.2 is present

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-em-motioncorr#45]
**Steps to reproduce**
Install plugin via plugin manager
Execute the motioncorr movie alignemtn protocol

**Versions**
Scipion 3.0.5
Plugin: 3.0.11
MotionCor2: 1.3.2

**Expected result**
Version for CUDA 10.2 will be executed

**Actual result**
software/em/motioncor2-1.3.2/bin/MotionCor2_1.3.2-Cuda101: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
00167:   ERROR: Movie  failed

**Comment by azazellochg** [comment]
Hi @DStrelak you are correct, at the moment there is no such check for cuda version in any plugin, so a default is used (you can see it in "scipion config -p motioncor2") unless you change scipion.conf

**Comment by azazellochg** [comment]
Same as https://github.com/scipion-em/scipion-em/issues/301
