### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by davidhoover** [scipion-em/scipion-em-motioncorr#71]
I installed scipion and motioncor2 and tried running the test and it immediately failed.  What did I do wrong?

(scipion3) scipion test motioncorr.tests.test_protocols_motioncor2.TestMotioncor2AlignMovies
Scipion v3.0.11 - Eugenius
Running tests....
Creating project at /spin1/users/hooverdm/private/apps/scipion/ScipionUserData/projects/TestMotioncor2AlignMovies/project.sqlite
>>>> python3 /usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download movies 
Selected datasets: movies
Local copy of dataset movies detected.
Checking for updates...
<urlopen error [Errno 110] Connection timed out>

==> Importing data - movies:
** Running command: 'python3 /usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/hooverdm/ScipionUserData/projects/TestMotioncor2AlignMovies" "Runs/000002_ProtImportMovies/logs/run.db" 2'
** Running command: 'python3 /usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/hooverdm/ScipionUserData/projects/TestMotioncor2AlignMovies" "Runs/000088_ProtImportMovies/logs/run.db" 88'

==> Testing motioncor2 - patch-based:
** Running command: 'python3 /usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/hooverdm/ScipionUserData/projects/TestMotioncor2AlignMovies" "Runs/000174_ProtMotionCorr/logs/run.db" 174'

*************** last 50 lines of STD OUT *********************

...... Frame (  2) shift:    -1.540     -1.550
...... Frame (  3) shift:    -2.650     -2.640
...... Frame (  4) shift:    -2.710     -2.950
...... Frame (  5) shift:    -2.520     -3.050
...... Frame (  6) shift:    -2.220     -3.090
...... Frame (  7) shift:    -1.800     -2.970

Global shifts are corrected: 0.081931 sec
Start to align patches.
Align patch 1  3 left
Iteration  1  Error:     0.562
Iteration  2  Error:     0.057

Align patch 2  2 left
Iteration  1  Error:     9.377
Iteration  2  Error:     0.710
Iteration  3  Error:     0.064

Align patch 3  1 left
Iteration  1  Error:     3.080
Iteration  2  Error:     0.143

Align patch 4  0 left
Iteration  1  Error:     1.172
Iteration  2  Error:     0.126

Reference frame: 0

Fitting error: 0.000 pixel.
3D Fitting completed.

Patch alignment time: 0.14(sec)

Mag stretch: 1.000  -0.000

Correction of local motion: 0.336377 sec

Computation time: 1.164450 sec
Total time: 4.950047 sec
Erasing.....movieFolder: Runs/000174_ProtMotionCorr/tmp/movie_000001
FINISHED: processMovieStep, step 2, time 2022-10-04 11:29:31.028927
ERROR: Movie Runs/000088_ProtImportMovies/extra/cct_1.em couldn't be added to the output set.
[Errno 2] No such file or directory: 'Runs/000174_ProtMotionCorr/extra/cct_1_aligned_mic-Patch-Full.log'
STARTED: waitForThreadStep, step 3, time 2022-10-04 11:29:31.391510
FINISHED: waitForThreadStep, step 3, time 2022-10-04 11:29:41.409740
STARTED: createOutputStep, step 4, time 2022-10-04 11:29:41.423515
FAILED: createOutputStep, step 4, time 2022-10-04 11:29:41.431267
------------------- PROTOCOL FAILED (DONE 4/4)
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 4/4)

*************** end of STD OUT *********************

*************** last 50 lines of STD ERR *********************

ERROR: Extra work (i.e plots, PSD, thumbnail) has failed for Runs/000174_ProtMotionCorr/tmp/movie_000001/cct_1.mrc

Couldn't prepare output details: [Errno 2] No such file or directory: 'Runs/000174_ProtMotionCorr/extra/cct_1_aligned_mic-Patch-Full.log'
Traceback (most recent call last):
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
    self._run()
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
    resultFiles = self._runFunc()
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
    return self._func(*self._args)
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_align_movies.py", line 142, in createOutputStep
    raise Exception("All movies failed, didn't create outputMicrographs."
Exception: All movies failed, didn't create outputMicrographs.Please review movie processing steps above.
Protocol failed: All movies failed, didn't create outputMicrographs.Please review movie processing steps above.

*************** end of STD ERR *********************

[   FAILED ] TestMotioncor2AlignMovies.test_cct_motioncor2_patch

Traceback (most recent call last):
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/motioncorr/tests/test_protocols_motioncor2.py", line 107, in test_cct_motioncor2_patch
    self.launchProtocol(prot)
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 116, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol cct - motioncor2 test1 (patch-based) execution failed. See last log lines above for more details.

**Comment by azazellochg** [comment]
Hi, can I see run.stdout?

**Comment by azazellochg** [comment]
most likely this was fixed recently in plugin v3.10
