### ISSUE TITLE
Readme file update MOTIONCOR2_BIN to MOTIONCOR2_PROGRAM

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-motioncorr#74]
I needed to set up motioncorr binary (cuda10.2 is horrible). Thank you for providing the option of setting a different cuda for motioncorr in the config file! I have a feeling that you did this specifically due to cuda10.2 :-) its just horrible! 
However, the readme file said to change MOTIONCOR2_BIN while the actual thing to change is MOTIONCOR2_PROGRAM

Cheers
Mohamad

**Comment by azazellochg** [comment]
@pconesa this is exactly why I didnt like this change. 
@MohamadHarastani the README is correct, these vars are for different things. Check your scipion3 config -p motioncorr to find the difference.

**Comment by pconesa** [comment]
I think we introduced MOTIONCOR2_PROGRAM to be have the "full final path" so the "default" validation could happen.

If you don't like this, we could always remove it. But I'd then add a validation in the protocol _validate to inform properly about the wrong configuration and which variable to change.

I agree that now the default "validation" says to change MOTIONCOR2_PROGRAM, which is not ideal. Am I getting it right?

**Comment by azazellochg** [comment]
yes, validation will print a msg about MOTIONCOR2_PROGRAM :(

**Comment by MohamadHarastani** [comment]
I cannot try to play with the configuration today, but somehow, I feel that MOTIONCOR2_BIN was useless and I had to change MOTIONCOR2_PROGRAM in order to run the program with a different cuda. I will verify and return back to you asap!

**Comment by MohamadHarastani** [comment]
I tested to play with these variables in scipion.config
Changing MOTIONCOR2_BIN didn't have any effect on running motioncorr. I set it to a random value and nothing changed.
MOTIONCOR2_PROGRAM controls everything.

**Comment by azazellochg** [comment]
you should not use both at the same time, MOTIONCOR2_PROGRAM has priority over other two vars (home and bin).

**Comment by azazellochg** [comment]
@pconesa I think this would help:
![image](https://user-images.githubusercontent.com/6952870/204143336-208a8080-a408-4044-a0d9-ccb760a4c309.png)
