### ISSUE TITLE
Be more "gentle" when MOTIONCORR_HOME is not valid to extract de version

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-motioncorr#89]
If user has a wrong value or points to a local motioncor installation without our "motioncorr-1.6.4" not only the protocol fails but scipion project load fails.

Scipion will tolerate this in the next release, but the error message is not clear that it is caused by a wrong MOTIONCORR_HOME or if valid, not able to detect the version....

**Comment by azazellochg** [comment]
Hi @pconesa how can I reproduce this? The following works without any errors:

MOTIONCOR_HOME = /public/EM/Scipion/scipion-dev/software/em/motioncor2
MOTIONCOR_CUDA_LIB = /public/EM/CUDA/cuda-11.8/lib64
MOTIONCOR_BIN = MotionCor2_1.6.4_Cuda118_Mar312023

/public/EM/Scipion/scipion-dev/software/em/motioncor2/bin/MotionCor2_1.6.4_Cuda118_Mar312023  -InMrc "cct_1.mrc" -Throw 0 -Trunc 0 -Patch 2 2 -MaskCent 0 0 -MaskSize 1 1 -FtBin 1.0 -Tol 0.2 -PixSize 1.0 -kV 300.0 -Cs 0 -OutStack 0 -Gpu 0 -SumRange 0.0 0.0 -LogDir ./ -InitDose 0 -FmDose 1.3 -Group 1 4 -OutMrc "cct_1_aligned_mic.mrc"
